# Generated by Django 4.0.7 on 2024-06-26 16:14

import bubook.book.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to=bubook.book.models.Book.upload_location)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.category')),
                ('tags', models.ManyToManyField(related_name='books', to='book.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
